@startuml System Context Diagram
!include <C4/C4_Container>

left footer C4 - Context Diagram - StudieTips

Person(mod, "Moderator", "Modererer/filtrerer indkomne tips fra studerende")
Person(student, "Studerende", "Studerende på universitetet")

System(StudieTips, "StudieTips", "Tips platform for studerende")

ContainerDb_Ext(Database, "Database","MS SQL Server","Opbevarer Tips and Bruger information")


Rel(mod, StudieTips, "Uses", "HTTP")
Rel(student, StudieTips, "Uses", "HTTP")
Rel(StudieTips, Database, "Uses", "SQL")

@enduml