@startuml Indledende sekvens diagram

mainframe **sd** Indledende Sekvens Diagram
hide footbox
actor       Studerende       as stud
boundary       ":DegreesViewIndex"       as degreesindex
control       ":DegreesController"       as degreescont
boundary       ":CoursesViewIndex"       as coursesindex
control       ":CoursesController"       as coursescont
control       ":TipsController"       as tipscont
boundary       ":TipsViewIndex"       as tipsindex
boundary       ":DegreeRepository"       as degreesrepo
boundary       ":CourseRepository"       as coursesrepo
boundary       ":TipsRepository"       as tipsrepo
database       ":DatabaseContext"       as db

/'entity       TipsModel       as tipsmodel'/


stud -> degreescont: http GET Index()

Activate degreescont
degreescont -> degreesrepo: GetDegrees()

Activate degreesrepo
degreesrepo -> db++: LINQ Query
db --> degreesrepo--: List<Degree>
degreesrepo --> degreescont: List<Degree>
Deactivate degreesrepo

degreescont -> degreesindex: View(List<Degree>)
activate degreesindex
degreesindex --> degreescont: DegreeView
deactivate degreesindex
degreescont --> stud: http Response
Deactivate degreescont

stud -> degreescont: http POST Redirect(int, string)

Activate degreescont
degreescont -> coursescont: Index(int)
Deactivate degreescont

Activate coursescont
coursescont -> coursesrepo: FindCourses(int)


Activate coursesrepo
coursesrepo -> db++: LINQ Query
db --> coursesrepo--: List<Course>
coursesrepo --> coursescont: List<Course>
Deactivate coursesrepo

coursescont -> coursesindex: View(List<Course>)
activate coursesindex
coursesindex --> coursescont: CourseView
deactivate coursesindex
coursescont --> stud: http Response
Deactivate coursescont

Deactivate coursescont

stud -> coursescont: http POST Redirect(int, string)

Activate coursescont
coursescont -> tipscont: Index(int)
Deactivate coursescont

Activate tipscont
tipscont -> tipsrepo: GetTips(int, string)

Activate tipsrepo
tipsrepo -> db++ : LINQ Query
db --> tipsrepo--: List<Tip>
tipsrepo --> tipscont: List<Tip>
Deactivate tipsrepo
tipscont -> tipsindex: View(List<Tip>)
activate tipsindex
tipsindex --> tipscont: TipView
deactivate tipsindex
tipscont --> stud: http Response
Deactivate tipscont

Deactivate tipscont


@enduml