@startuml
mainframe **sd** Use Case 2 - læs tip
hide footbox
actor       Studerende       as stud
boundary       ":TipsViewIndex"       as tipsindex

stud -> tipsindex: Trykker på ønsket tip for at læse mere

note left
Første del af use casen
er udeladt og kan ses
i sekvensdiagrammet
"Indledende sekvensdiagram"
end note

@enduml
