@startuml

title Use Case 4 - Godkend/Afvis tip
hide footbox
actor       "Moderator"       as mod
control       ":ModeratorController"       as modcont
boundary       ":NavigationBarView"       as navbar
boundary       ":ModeratorViewIndex"       as modindex
boundary       ":TipRepository"       as tipsrepo
database       ":DatabaseContext"       as db

mod -> modcont: Index(string, int)

Activate modcont
modcont -> tipsrepo: GetUnmoderatedTips()

Activate tipsrepo
tipsrepo -> db: LINQ Query

Activate db
db --> tipsrepo: IQueryable<Tip>
Deactivate db

tipsrepo --> modcont: List<Tip>
Deactivate tipsrepo

modcont -> modindex: UpdateView(List<Tip>)

Activate modindex
modindex --> modcont: View()
Deactivate modindex

modcont --> mod: http response
Deactivate modcont


mod --> modcont: VerifyTip(int)

Activate modcont
modcont -> tipsrepo: GetTip(int)

Activate tipsrepo
tipsrepo -> db: LINQ Query

Activate db
db --> tipsrepo: IQueryable<Tip>
Deactivate db

tipsrepo --> modcont: Tip
Deactivate tipsrepo

modcont -> modcont :Tip.isVerified = true
modcont -> tipsrepo: SaveChanges()

Activate tipsrepo
tipsrepo -> db: SaveChanges()

Activate db
db --> tipsrepo: OK
Deactivate db

tipsrepo --> modcont: OK
Deactivate tipsrepo

modcont -> tipsrepo: GetUnmoderatedTips()

Activate tipsrepo
tipsrepo -> db: LINQ Query

Activate db
db --> tipsrepo: IQueryable<Tip>
Deactivate db

tipsrepo --> modcont: List<Tip>
Deactivate tipsrepo

modcont -> modindex: UpdateView(List<Tip>)

Activate modindex
modindex --> modcont: View()
Deactivate modindex

modcont --> mod: http response
Deactivate modcont




@enduml