@startuml

mainframe **Use Case 5 - Fjern tip**

actor       Moderator       as mod
control       TipsController       as tipscont
boundary       HomeViewIndex       as homeindex
boundary       TipsViewIndex       as tipsindex
boundary       TipsViewDelete       as tipsdelete
boundary       TipRepository       as tipsrepo
database       DatabaseContext       as db


mod -> tipscont: http GET Delete(int)

note left
Første del af use casen
er udeladt og kan ses
i sekvensdiagrammet
"Indledende sekvensdiagram"
end note

Activate tipscont
tipscont -> tipsrepo: GetTipDetails(int)

Activate tipsrepo
tipsrepo -> db: query

Activate db
db --> tipsrepo: IQueryable<Tip>
Deactivate db

tipsrepo --> tipscont: IQueryable<Tip>
Deactivate tipsrepo

tipscont -> tipsdelete: UpdateView(int)

Activate tipsdelete
tipsdelete --> tipscont: View()
Deactivate tipsdelete

tipscont --> mod: http response
Deactivate tipscont

mod -> tipscont: http DELETE DeleteConfirmed(int)

Activate tipscont
tipscont -> tipsrepo: DeleteTip(int)

Activate tipsrepo
tipsrepo -> db: Remove(Tip)

Activate db
db --> tipsrepo: OK
Deactivate db

tipsrepo ->> db: SaveChangesAsync()

tipsrepo --> tipscont: OK
Deactivate tipsrepo

tipscont -> tipsrepo: GetTips(int, string)

Activate tipsrepo
tipsrepo --> db: query

Activate db
db --> tipsrepo: IQueryable<Tip>
Deactivate db

tipsrepo --> tipscont: IQueryable<Tip>
Deactivate tipsrepo

tipscont -> tipsindex: UpdateView(List<Tip>)

Activate tipsindex
tipsindex --> tipscont: View()
Deactivate tipsindex

tipscont --> mod: http response
Deactivate tipscont


hide footbox
@enduml
