@startuml Component Diagram Web App
!include <C4/C4_Container>
!include <C4/C4_Component>

left to right direction

Container_Boundary(webapp,"Web Application",""){
    Component(C1, "HTTPS-Message-Receiver", "Component: technology")
    Component(C2, "MSSQL-Query-Handler", "Component: technology")
} 

@enduml