@startuml Container Diagram
!include <C4/C4_Container>

skinparam linetype ortho

Person(User, "Studerende")
Person(Moderator, "Moderator")

System_Boundary(c1, "StudieTips") {

    Container(web_app, "Web Application", "Container: C#, Razor", "Allows users to browse and add tips")

    Container(API, "Back-End API", "Container: C#, ASP.NET Core 5 MVC", "Allows Web-Application to interface with database")
    
    
}
ContainerDb_Ext(Database, "Database","Container: MS SQL Server","Stores Tips and User information")

Moderator -[hidden]left- web_app

Rel(User, web_app, "Uses", "HTTPS")
Rel(Moderator, web_app, "Uses", "HTTPS")
Rel(API, web_app, "Returns", "HTTPS/JSON")
Rel(web_app, API, "Makes API calls to", "HTTPS/JSON")
Rel(Database, API, "Queries for data", "MSSQL")
Rel_U(API, Database, "Returns", "MSSQL")

@enduml