@startuml
!include <C4/C4_Container>
!include <C4/C4_Component>

'Person(User, "Studerende")
'Person(Moderator, "Moderator")

Container_Boundary(API,"API",""){
    
    Component(Repository1, "Course Repository", "Component: ASP.NET Repository","Handles fetching and adding new courses")
    Component(Repository2, "Class Repository", "Component: ASP.NET Repository","Handles fetching and adding new classes")
    Component(Repository3, "Tip Repository", "Component: ASP.NET Repository","Handles fetching and adding new tips")
    Component(Repository4, "Login Repository", "Component: ASP.NET Repository","Handles validation for login")    
} 
'Container(Backend, "Backend","Container: MS SQL Server","Stores Tips and User information")

'Rel(User, webapp, "Access")
'Rel(Moderator, webapp, "Access")
'Rel(webapp, Backend,"Reads from and writes to")
@enduml