@startuml
!include <C4/C4_Container>
!include <C4/C4_Component>

'Person(User, "Studerende")
'Person(Moderator, "Moderator")

Container_Boundary(webapp,"WebApplication",""){
    Component(View1, "FrontPage View", "Component: ASP.NET Razor View")
    Component(View2, "CourseList View", "Component: ASP.NET Razor View")
    Component(View3, "ClassList View", "Component: ASP.NET Razor View")
    Component(View4, "TipsPageView", "Component: ASP.NET Razor View")
    Component(View5, "Add Tip View", "Component: ASP.NET Razor View")
    Component(View6, "LoginPage View", "Component: ASP.NET Razor View")
    
    
} 
'Container(Backend, "Backend","Container: MS SQL Server","Stores Tips and User information")

'Rel(User, webapp, "Access")
'Rel(Moderator, webapp, "Access")
'Rel(webapp, Backend,"Reads from and writes to")
@enduml