@startuml
title Use Case 1 - Tilføj tip

actor       Studerende       as stud
boundary       TipsViewIndex       as tipsindex
boundary       TipsViewCreate       as tipscreate
control       TipsController       as tipscont
boundary       TipsRepository       as tipsrepo
database       Database       as db

/'entity       TipsModel       as tipsmodel'/

stud -> tipsindex: Trykker på knap som indsætter tip

note left
Første del af use casen
er udeladt og kan ses
i sekvensdiagrammet A1
end note

Activate tipsindex
tipsindex -> tipscont: Create(int)
Deactivate tipsindex

Activate tipscont
tipscont --> tipscreate: View()
Deactivate tipscont

stud -> tipscreate: Indtaster og sender tip

Activate tipscreate
tipscreate -> tipscont: Create(Tip)
Deactivate tipscreate

Activate tipscont
tipscont -> tipsrepo: Add(Tip)
Deactivate tipscont

Activate tipsrepo
tipsrepo -> db: Add(Tip)
tipsrepo -> db: SaveChangesAsync()
Deactivate tipsrepo


@enduml