@startuml
title Use Case 2 - Læs tip

actor       Studerende       as stud
boundary       TipsViewIndex       as tipsindex

stud -> tipsindex: Trykker på ønsket tip for at læse mere

note left
Første del af use casen
er udeladt og kan ses
i sekvensdiagrammet A1
end note

@enduml