@startuml

title Use Case 3 - Søg Tip

actor       Studerende       as stud
control       TipsController       as tipscont
boundary       TipsViewSearchTip       as tipssearch
boundary       TipRepository       as tipsrepo
database       DatabaseContext       as db


stud -> tipscont: http POST SearchTip(SearchDto)

Activate tipscont
tipscont -> tipsrepo: GetTipsWithinSearchTerm(SearchDto)

Activate tipsrepo
tipsrepo -> db: query 

Activate db
db --> tipsrepo: IQueryable<Tip>
Deactivate db

tipsrepo --> tipscont: IQueryable<Tip>
Deactivate tipsrepo

tipscont -> tipssearch: UpdateView(List<Tip>)

Activate tipssearch
tipssearch --> tipscont: View()
Deactivate tipssearch

tipscont --> stud: http response
Deactivate tipscont



hide footbox

@enduml
