@startuml

title Use Case 4 - Godkend/Afvis tip

actor       Moderator       as mod
boundary       NavigationBarView       as navbar
boundary       ModeratorViewIndex       as modindex
control       ModeratorController       as modcont
boundary       TipsRepository       as tipsrepo
database       Database       as db

mod -> navbar: Trykker på Moderator-side

Activate navbar
navbar -> modcont: Index()
Deactivate navbar

Activate modcont
modcont -> tipsrepo: GetUnmoderatedTips()

Activate tipsrepo
tipsrepo -> db: execute
db --> tipsrepo: results
tipsrepo --> modcont: results
Deactivate tipsrepo

modcont -> modindex: View('results')
Deactivate modcont

mod -> modindex: Trykker for at verificere tip

Activate modindex
modindex -> modcont: VerifyTip(int)
Deactivate modindex

Activate modcont
modcont -> tipsrepo: GetTip(int)

Activate tipsrepo
tipsrepo -> db: execute
db --> tipsrepo: results
tipsrepo --> modcont: results
Deactivate tipsrepo

modcont -> modcont: results.isVerified = true
modcont -> tipsrepo: SaveChanges()

Activate tipsrepo
tipsrepo -> db: execute
Deactivate tipsrepo

modcont -> modindex: Redirect(nameof('Index')
Deactivate modcont



@enduml