@startuml

hide empty fields
hide empty methods

!include .\..\Controllers\CoursesController.puml
!include .\..\Models\Degree.puml
!include .\..\Models\Course.puml
!include .\..\Models\ViewModels\DegreeCourse.puml
!include .\..\Models\Tip.puml
!include .\..\Repository\CourseRepository.puml
!include .\..\Repository\ICourseRepository.puml
!include .\..\Repository\DegreeRepository.puml
!include .\..\Repository\IDegreeRepository.puml

@enduml