@startuml
!include <C4/C4_Container>
!include <C4/C4_Component>

Person(User, "Studerende")
Person(Moderator, "Moderator")

Container_Boundary(webapp,"Add Tips Page",""){
    Component(View, "AddTipsPageView", "Component: ASP.NET MVC Razor View")
    

    Component(Controller, "AddTipsPageController", "Component: ASP.NET MVC Controller")
    

    Component(Model, "AddTipsPageModel", "Component: ASP.NET MVC Model")

    
    Component(Repo, "AddTipsRepository", "Component: Repository")
    
} 
ContainerDb_Ext(Database, "Database","Container: MS SQL Server","Stores Tips and User information")


Lay_R(User,Moderator)
Lay_D(User,Controller)
Lay_D(Moderator,Controller)
Lay_R(Model,View)
Lay_R(Model,Database)

Rel(User, Controller, "Access")
Rel(Moderator, Controller, "Access")
Rel(Controller, Model, "Manipulates")
Rel(Model, View, "Updates")
Rel(Model, Repo,"Interfaces with")
Rel(Repo, Database,"Reads from and writes to")
@enduml