@startuml Component Diagram Views
!include <C4/C4_Container>
!include <C4/C4_Component>

left footer "   C4 - Component Diagram - Views - StudieTips"

Container_Boundary(Views,"Views",""){
    Component(View1, "FrontPage View", "Component: ASP.NET Razor View")
    Component(View2, "DegreeList View", "Component: ASP.NET Razor View")
    Component(View3, "CourseList View", "Component: ASP.NET Razor View")
    Component(View4, "TipsPageView", "Component: ASP.NET Razor View")
    Component(View5, "Add Tip View", "Component: ASP.NET Razor View")
    Component(View7, "Menu view", "Component: ASP.NET Razor View", "Partial view to reuse the menu for all full views.")
    
    
} 

Lay_D(View1,View2)
Lay_D(View3,View4)

Rel_R(View1,View7,"Utilizes")
Rel_R(View2,View7,"Utilizes")
Rel_R(View3,View7,"Utilizes")
Rel_R(View4,View7,"Utilizes")
Rel_U(View5,View7,"Utilizes")
@enduml