@startuml
!include <C4/C4_Container>
!include <C4/C4_Component>

left footer "   C4 - Component Diagram - API - StudieTips"

Container_Boundary(API,"API",""){
    
    Component(Repository1, "Degree Repository", "Component: ASP.NET Repository","Handles fetching and adding new degrees")
    Component(Repository2, "Course Repository", "Component: ASP.NET Repository","Handles fetching and adding new Courses")
    Component(Repository3, "Tip Repository", "Component: ASP.NET Repository","Handles fetching and adding new tips")
    Component(Repository4, "Login Repository", "Component: ASP.NET Repository","Handles validation for login")    
}

@enduml