@startuml
!include <C4/C4_Container>
!include <C4/C4_Component>

Person(User, "Studerende")
Person(Moderator, "Moderator")

Container_Boundary(webapp,"Front Page",""){
    Component(FrontView, "FrontPageView", "Component: ASP.NET MVC Razor View")
    

    Component(FrontController, "FrontPageController", "Component: ASP.NET MVC Controller")
    

    Component(FrontModel, "FrontPageModel", "Component: ASP.NET MVC Model")

    
    'Component(Repo, "UserRepo", "Component: Repository")
    
} 
'ContainerDb_Ext(Database, "Database","Container: MS SQL Server","Stores Tips and User information")


Lay_R(User,Moderator)
Lay_D(User,FrontController)
Lay_D(Moderator,FrontController)
Lay_R(FrontModel,FrontView)
'Lay_R(FrontModel,Database)

Rel(User, FrontController, "Access")
Rel(Moderator, FrontController, "Access")
Rel(FrontController, FrontModel, "Manipulates")
Rel(FrontModel, FrontView, "Updates")
'Rel(FrontModel, Repo,"Interfaces with")
'Rel(Repo, Database,"Reads from and writes to")
@enduml

