@startuml
title Use Case 1 - Tilføj tip

actor       ":Studerende"       as stud
control       ":TipsController"       as tipscont
boundary       ":TipsViewCreate"       as tipscreate
boundary       ":TipsViewIndex"       as tipsindex
boundary       ":TipRepository"       as tipsrepo
database       ":DatabaseContext"       as db


stud -> tipscont: Trykker på "Tilføj tips"

note left
Første del af use casen
er udeladt og kan ses
i sekvensdiagrammet A1
end note


Activate tipscont
tipscont -> tipscreate: Henter "Tilføj Tip"-side

Activate tipscreate
tipscreate --> tipscont: Returnerer "Tilføj tip"-side
Deactivate tipscreate

tipscont --> stud: Viser "Tilføj Tip"-side

Deactivate tipscont

stud -> tipscont: Indsender tip

Activate tipscont
tipscont -> tipsrepo: Tilføjer tip

Activate tipsrepo
tipsrepo -> db: Tilføjer tip til database

Activate db
db --> tipsrepo: OK
Deactivate db

tipsrepo ->> db: Gemmer ændringer

tipsrepo --> tipscont: OK
Deactivate tipsrepo

tipscont -> tipsrepo: Henter tips

Activate tipsrepo
tipsrepo -> db: Henter tips

Activate db
db --> tipsrepo: Returnerer liste med tips
Deactivate db

tipsrepo --> tipscont: Returnerer liste med tips

Deactivate tipsrepo

tipscont -> tipsindex: Henter tipsside med liste af tips
Activate tipsindex
tipsindex --> tipscont: Returnerer tipsside
Deactivate tipsindex

tipscont --> stud: Viser tipsside
Deactivate tipscont


hide footbox

@enduml
