@startuml

title Use Case 3 - Søg Tip

actor       Studerende       as stud
control       TipsController       as tipscont
boundary       TipsViewSearchTip       as tipssearch
boundary       TipRepository       as tipsrepo
database       DatabaseContext       as db


stud -> tipscont: Indtaster og indsender søgeord

Activate tipscont
tipscont -> tipsrepo: Henter tips med det specifikke søgeord

Activate tipsrepo
tipsrepo -> db: Henter tips med det specifikke søgeord

Activate db
db --> tipsrepo: Returnerer liste som passer med søgeord
Deactivate db

tipsrepo --> tipscont: Returnerer liste
Deactivate tipsrepo

tipscont -> tipssearch: Henter tips som passer med søgeord

Activate tipssearch
tipssearch --> tipscont: Returnerer tips
Deactivate tipssearch

tipscont --> stud: Viser tipsside
Deactivate tipscont



hide footbox

@enduml

hide footbox

@enduml
