@startuml

mainframe **Use Case 5 - Fjern tip**

actor       Moderator       as mod
control       TipsController       as tipscont
boundary       HomeViewIndex       as homeindex
boundary       TipsViewIndex       as tipsindex
boundary       TipsViewDelete       as tipsdelete
boundary       TipRepository       as tipsrepo
database       DatabaseContext       as db


mod -> tipscont: Trykker på "Slet tip"

note left
Første del af use casen
er udeladt og kan ses
i sekvensdiagrammet
"Indledende sekvensdiagram"
end note

Activate tipscont
tipscont -> tipsrepo: Henter information om tippet

Activate tipsrepo
tipsrepo -> db: Henter tip

Activate db
db --> tipsrepo: Returnerer tip
Deactivate db

tipsrepo --> tipscont: Returnerer tip
Deactivate tipsrepo

tipscont -> tipsdelete: Henter "Slet tip"-side

Activate tipsdelete
tipsdelete --> tipscont: Returnerer "Slet tip"-side
Deactivate tipsdelete

tipscont --> mod: Viser "Slet tip"-side
Deactivate tipscont

mod -> tipscont: Trykker på slet

Activate tipscont
tipscont -> tipsrepo: Finder tip som skal slettes

Activate tipsrepo
tipsrepo -> db: Finder tip

Activate db
db --> tipsrepo: OK
Deactivate db

tipsrepo ->> db: Gemmer ændringer

tipsrepo --> tipscont: OK
Deactivate tipsrepo

tipscont -> tipsrepo: Henter alle tips

Activate tipsrepo
tipsrepo --> db: Henter alle tips

Activate db
db --> tipsrepo: Returnerer tips
Deactivate db

tipsrepo --> tipscont: Returnerer tips
Deactivate tipsrepo

tipscont -> tipsindex: Henter tipsside

Activate tipsindex
tipsindex --> tipscont: Returnerer tipsside
Deactivate tipsindex

tipscont --> mod: Viser tipsside
Deactivate tipscont


hide footbox
@enduml
