@startuml LogoutSequenceDiagram


actor User as User
participant LoginPartialView as LoginPartialView
participant MicrosoftIdentitySystem as  MicrosoftIdentitySystem
participant HomeController as HomeController

User -> LoginPartialView : clicks on "log out"
activate LoginPartialView

LoginPartialView -> MicrosoftIdentitySystem : sends action
deactivate LoginPartialView

activate MicrosoftIdentitySystem
MicrosoftIdentitySystem -> MicrosoftIdentitySystem : Creates LogoutView

MicrosoftIdentitySystem -> MicrosoftIdentitySystem : End user session

MicrosoftIdentitySystem -> HomeController : returns action
deactivate MicrosoftIdentitySystem

activate HomeController
HomeController -> HomeController : Create home view
deactivate HomeController

@enduml