@startuml
left to right direction
skinparam actorStyle awesome
package AC_StudieTips{
database Database
card StudieTips
:Studerende: -- StudieTips
:Moderator: -- StudieTips
StudieTips -- Database

}
@enduml