@startuml
skinparam linetype ortho
hide empty fields
hide empty methods

left to right direction

!include .\C4\includes\Data\DatabaseContext.puml
together InterfaceRepos {
!include .\C4\includes\\Repository\IDegreeRepository.puml
!include .\C4\includes\\Repository\ICourseRepository.puml
!include .\C4\includes\\Repository\ITipRepository.puml
}

!include .\C4\includes\\Models\ViewModels\DegreeCourse.puml
!include .\C4\includes\\Models\Tip.puml
!include .\C4\includes\\Models\Degree.puml
!include .\C4\includes\\Models\Course.puml
!include .\C4\includes\\Models\Tip.puml
!include .\C4\includes\\Models\SearchDto.puml


together Repos {
!include .\C4\includes\\Repository\CourseRepository.puml
!include .\C4\includes\\Repository\DegreeRepository.puml
!include .\C4\includes\\Repository\TipRepository.puml
}
together Controllers {
!include .\C4\includes\\Controllers\HomeController.puml
!include .\C4\includes\\Controllers\DegreesController.puml
!include .\C4\includes\\Controllers\CoursesController.puml
!include .\C4\includes\\Controllers\TipsController.puml
!include .\C4\includes\\Controllers\ModeratorController.puml
}


@enduml
