@startuml Container Diagram
!include <C4/C4_Container>

left footer C4 - Container Diagram - StudieTips

Person(Moderator, "Moderator")
Person(User, "Studerende")

System_Boundary(c1, "StudieTips") {
    Container(Views, "Views", "Container: C#, ASP.NET Core 5 Static Views", "Danner statiske views for brugeren")
    Container(WebApplication, "Web Application", "Container: C#, ASP.NET Core 5 Controller & Models", "Kontrollerer bruger-input og modeller")
    Container(API, "Repository", "Container: C#, ASP.NET Core 5 Repositories", "Grænseflade funktionalitet mellem database og system")
}
ContainerDb_Ext(Database, "Database","Container: MS SQL Server","Stores Tips and User information")

Lay_D(User,c1)
Lay_D(Moderator,c1)
Lay_R(Views,WebApplication)

Rel(User,Views, "Ser og indsender tips")
Rel(Moderator, Views, "Ser og modererer tips")


Rel(User,WebApplication, "Besøger studietips.com", "HTTPS")
Rel(Moderator, WebApplication, "Besøger studietips.com", "HTTPS")

Rel(WebApplication,Views, "Afleverer siden som er valgt")

Rel(WebApplication,API, "Henter data fra")

Rel(API,Database, "Søger efter data")




@enduml